"""empty message

Revision ID: 12577ec844d7
Revises: 409335819de7
Create Date: 2020-04-24 19:53:12.403909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12577ec844d7'
down_revision = '409335819de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'website',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('Venue_website_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_website_key', 'Venue', ['website'])
    op.alter_column('Venue', 'website',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
